version: '3.8'

services:
  nlp-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    restart: unless-stopped
    command: python run.py --host 0.0.0.0 --port 8000

  # Optional: Add a simple UI for demonstration
  nlp-ui:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./ui:/usr/share/nginx/html
    depends_on:
      - nlp-api
    restart: unless-stopped
